accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'


urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('register/', views.user_register, name='register'),
    path('logout/', views.user_logout, name='logout'),
]

blog/urls.py
from django.urls import path
from . import views


app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('category/<slug:slug>/', views.post_list, name='category'),
    path(
        '<int:year>/<int:month>/<int:day>/<slug:post>/', 
        views.post_detail, 
        name='post_detail'
    ),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'


urlpatterns = [
    path('resume/', views.resume, name='resume'),
    path('contact/', views.contact, name='contact'),
    path('', views.index, name='index'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView


from fcm_django.api.rest_framework import FCMDeviceAuthorizedViewSet
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register('devices', FCMDeviceAuthorizedViewSet)



urlpatterns = [
    path("firebase-messaging-sw.js",
        TemplateView.as_view(
            template_name="firebase-messaging-sw.js",
            content_type="application/javascript",
        ),
        name="firebase-messaging-sw.js"
    ),

    path('admin/', admin.site.urls),
    path('api/', include(router.urls)),
    path('', include('main.urls', namespace='main')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from typing import Iterable, Optional
from django.db import models

from .services import (
    upload_sertificate_path, upload_coding_lang_path,
    upload_quote_path, upload_cv_path
)


class SocialNetwork(models.Model):
    name = models.CharField(max_length=50, unique=True)
    url = models.URLField(max_length=200)
    is_active = models.BooleanField(default=True)
    order = models.PositiveSmallIntegerField(default=0, blank=True, null=True)

    class Meta:
        ordering = ['order',]

    def __str__(self):
        return self.name
    

class Education(models.Model):
    edu_name = models.CharField(max_length=250, unique=True) 
    year = models.CharField(max_length=50) 
    specialty = models.CharField(max_length=50)
    about = models.CharField(max_length=50)

    def __str__(self):
        return self.edu_name
    

class Experience(models.Model):
    company = models.CharField(max_length=250, unique=True) 
    year = models.CharField(max_length=50) 
    specialty = models.CharField(max_length=50)
    about = models.CharField(max_length=50)

    def __str__(self):
        return self.company
    

class Sertificate(models.Model):
    name = models.CharField(max_length=100)
    company = models.CharField(max_length=50)
    logo = models.ImageField(upload_to=upload_sertificate_path)
    image = models.ImageField(upload_to=upload_sertificate_path)
    year = models.DateField(blank=True, null=True)
    is_active = models.BooleanField(default=True)
    order = models.PositiveSmallIntegerField(blank=True, null=True)

    class Meta:
        ordering = ['order',]

    def __str__(self):
        return self.name
    

class CodingLanguage(models.Model):
    name = models.CharField(max_length=30)
    logo = models.ImageField(upload_to=upload_coding_lang_path)
    is_active = models.BooleanField(default=True)
    order = models.PositiveSmallIntegerField(blank=True, null=True)

    class Meta:
        ordering = ['order',]

    def __str__(self):
        return self.name


class Quote(models.Model):
    author = models.CharField(max_length=100)
    body = models.CharField(max_length=300)
    from_where = models.CharField(max_length=100)
    image = models.ImageField(upload_to=upload_quote_path)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.name} -> {self.from_where}"
    

class FunFact(models.Model):
    projects = models.PositiveSmallIntegerField(default=1)
    clients = models.PositiveSmallIntegerField(default=1)
    work_hour = models.PositiveSmallIntegerField(default=0)
    posts = models.PositiveSmallIntegerField(default=0)
    cv = models.FileField(upload_to=upload_cv_path, blank=True, null=True)
    about_me = models.CharField(max_length=350, blank=True)

    def save(self, *args, **kwargs):
        if FunFact.objects.exists():
            raise ValueError("You can add only one item for this model")
        else:
            super().save(self, *args, **kwargs)

class Contact(models.Model):
    tel = models.CharField(max_length=20, blank=True)
    tel1 = models.CharField(max_length=20, blank=True)
    city = models.CharField(max_length=50, blank=True)
    region = models.CharField(max_length=50, blank=True)
    email = models.EmailField(max_length=50, blank=True)

    def __str__(self):
        return self.tel
    

class UserLetter(models.Model):
    full_name = models.CharField(max_length=100)
    email = models.EmailField(max_length=50)
    subject = models.CharField(max_length=100)
    body = models.CharField(max_length=150)

    def __str__(self):
        return f"{self.full_name} -> {self.subject}"

main/forms.py
from django import forms

from .models import UserLetter


class UserLetterForm(forms.ModelForm):
    
    class Meta:
        model = UserLetter
        fields = "__all__"
        widgets = {
            'body': forms.Textarea(attrs={"rows":7, "cols":10}),
        }
        

main/views.py
from django.shortcuts import render
from django.contrib import messages

from .models import (
    Education, Experience, Sertificate,
    CodingLanguage, Quote, FunFact, Contact, 
    UserLetter,
)

from .forms import UserLetterForm

def index(request):
    fun_facts = FunFact.objects.first()
    quotes = Quote.objects.filter(is_active=True)
    coding_languages = CodingLanguage.objects.filter(is_active=True)
    context = {
        'section': 'about',
        'fun_facts': fun_facts,
        'quotes': quotes,
        'coding_languages': coding_languages,        
    }
    return render(request, 'main/index.html', context)


def resume(request):
    education = Education.objects.all()
    experiece = Experience.objects.all()
    sertificates = Sertificate.objects.filter(is_active=True)
    coding_languages = CodingLanguage.objects.filter(is_active=True)
    context = {
        'section': 'resume',
        'education': education,
        'experiece': experiece,
        'sertificates': sertificates,
        'coding_languages': coding_languages
    }
    return render(request, 'main/resume.html', context)


def contact(request):
    contact = Contact.objects.first()
    form = UserLetterForm()
    if request.method == 'POST':
        form = UserLetterForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Your message has been sent successfully. We will contact you soon")
        else:
            messages.error(request, "There was an error sending the message.\nPlease check that all fields are filled in correctly and try again!")
    context = {
        'section': 'contact',
        'contact': contact,
        'form': form

    }
    return render(request, 'main/contact.html', context)

main/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" class="no-js">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge"> 
    <title>Leven - Resume / CV / vCard Template</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name="description" content="Leven - Resume / CV / vCard Template" />
    <meta name="keywords" content="vcard, resposnive, retina, resume, jquery, css3, bootstrap, portfolio" />
    <meta name="author" content="lmpixels" />
    <link rel="shortcut icon" href="favicon.ico">

    {% block styles %}
      <link rel="stylesheet" href="{% static 'css/normalize.css' %}" type="text/css">
      <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
      <link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}" type="text/css">
      <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}" type="text/css">
      <link rel="stylesheet" href="{% static 'css/main.css' %}" type="text/css">

      <script src="js/modernizr.custom.js"></script>
    {% endblock %} 
  </head>

  <body class="page">

    <div class="lm-animated-bg"></div>
    
    <!-- Loading animation -->
    <div class="preloader">
      <div class="preloader-animation">
        <div class="preloader-spinner">
        </div>
      </div>
    </div>
    <!-- /Loading animation -->

    <!-- Scroll To Top Button -->
    <div class="lmpixels-scroll-to-top"><i class="lnr lnr-chevron-up"></i></div>
    <!-- /Scroll To Top Button -->

    <div class="page-scroll">
      <div id="page_container" class="page-container bg-move-effect" data-animation="transition-flip-in-right">


        <!-- Header -->
        <header id="site_header" class="header">
          <div class="header-content clearfix">
                
            <!-- Text Logo -->
            <div class="text-logo">
              <a href="{% url 'main:index' %}">
                <div class="logo-symbol">I</div>
                <div class="logo-text">Islombek <span>Orifov</span></div>
              </a>
            </div>
            <!-- /Text Logo -->

            <!-- Navigation -->
            <div class="site-nav mobile-menu-hide">
              <ul class="leven-classic-menu site-main-menu">
                <li class="menu-item {% if section == 'about'%}current-menu-item{% endif %}">
                  <a href="{% url 'main:index' %}">About Me</a>
                </li>

                <li class="menu-item {% if section == 'resume'%}current-menu-item{% endif %}">
                  <a href="{% url 'main:resume' %}">Resume</a>
                </li>

                {% comment %} <li class="menu-item menu-item-has-children current-menu-item">
                  <a href="portfolio.html">Portfolio</a>
                  <ul class="sub-menu">
                    <li class="menu-item current-menu-item">
                      <a href="portfolio-2-columns.html">Portfolio 2 Columns</a>
                    </li>
                    <li class="menu-item">
                      <a href="portfolio.html">Portfolio 3 Columns</a>
                    </li>
                    <li class="menu-item">
                      <a href="portfolio-4-columns.html">Portfolio 4 Columns</a>
                    </li>
                    <li class="menu-item">
                      <a href="portfolio-5-columns.html">Portfolio 5 Columns</a>
                    </li>
                  </ul>
                </li> {% endcomment %}
                
                <li class="menu-item menu-item-has-children">
                  <a href="{% url 'blog:post_list' %}">Blog</a>
                  <ul class="sub-menu">
                    {% for category in categories%}
                      <li class="menu-item">
                        <a href="{{ category.get_absolute_url }}">{{ category.name }}</a>
                      </li>
                    {% endfor %}
                  </ul>
                </li>

                <li class="menu-item {% if section == 'contact'%}current-menu-item{% endif %}">
                  <a href="{% url 'main:contact' %}">Contact</a>
                </li>
                
                {% if request.user.is_anonymous %}
                  <li class="menu-item">
                    <a style="color: #007ced; !important" href="{% url 'accounts:login' %}">Login</a>
                  </li>
                {% else %}
                  <li class="">
                    <a style="color: #007ced; !important" href="{% url 'accounts:logout' %}">Logout</a>
                  </li>
                {% endif %}

              </ul>
            </div>

            <a class="menu-toggle mobile-visible">
                <i class="fa fa-bars"></i>
            </a>
          </div>
        </header>
        <!-- /Header -->

        <div id="main" class="site-main">
          {% block content %}
          {% endblock %}
        </div>

        <!-- Footer -->
        <footer class="site-footer clearfix">
          <div class="footer-social">
            <ul class="footer-social-links">
              {% for social in social_net %}
                <li>
                  <a href="{{ social.url }}" target="_blank">{{ social.name }}</a>
                </li>
              {% endfor %}
            </ul>
          </div>
              
          <div class="footer-copyrights">
            <p>© {{ current_year }} All rights reserved. Orifov Academy</p>
          </div>
        </footer>
        <!-- /Footer -->
        
      </div>
    </div>
    {% block sctipts %}
      <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
      <script src="{% static 'js/imagesloaded.pkgd.min.js' %}"></script>
      <script src='https://www.google.com/recaptcha/api.js'></script>
      <script src="{% static 'js/bootstrap.min.js' %}"></script>
      <script src="{% static 'js/jquery.shuffle.min.js' %}"></script>
      <script src="{% static 'js/masonry.pkgd.min.js' %}"></script>
      <script src="{% static 'js/owl.carousel.min.js' %}"></script>
      <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
      <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCrDf32aQTCVENBhFJbMBKOUTiUAABtC2o"></script>
      <script src="{% static 'js/jquery.googlemap.js' %}"></script>
      <script src="{% static 'js/validator.js' %}"></script>
      <script src="{% static 'js/main.js' %}"></script>

      <script src="https://www.gstatic.com/firebasejs/4.1.2/firebase.js"></script>
      <script src="{% static 'js/firebase1.js' %}"></script>
      <script>
        {% if not request.user.is_anonymous%}
          requestPermission();
        {% endif %}
      </script>
    {% endblock %}
  </body>
</html>